[package]
name = "dither"
version = "0.1.0"
authors = ["Evan Pacini <evan.pacini@gmail.com>"]
edition = "2021"
rust-version = "1.80.0"
description = "A simple dithering library"
license = "CC0-1.0"
keywords = ["dithering", "image", "graphics"]

[dependencies]
image = "0.25.4"
rand = "0.8.5"