condense_wildcard_suffixes = true
edition = "2021"
fn_params_layout = "Compressed"
fn_single_line = true
format_strings = true
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true
